/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdbcf",
        "on-error": "#ffffff",
        "surface-tint": "#5f5e5e",
        "surface-dim": "#dcd9d9",
        "on-tertiary-container": "#838b73",
        "on-surface": "#1c1b1b",
        "on-secondary": "#ffffff",
        "secondary-container": "#feb198",
        "tertiary": "#060c01",
        "on-secondary-fixed-variant": "#6d3825",
        "on-tertiary-fixed-variant": "#424935",
        "error-container": "#ffdad6",
        "primary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#ffb59c",
        "surface-variant": "#e5e2e1",
        "surface": "#fcf9f8",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c8c6c5",
        "surface-container-highest": "#e5e2e1",
        "inverse-primary": "#c8c6c5",
        "on-primary-fixed-variant": "#474746",
        "background": "#fcf9f8",
        "surface-container": "#f0eded",
        "on-background": "#1c1b1b",
        "outline-variant": "#c4c7c7",
        "surface-bright": "#fcf9f8",
        "on-primary": "#ffffff",
        "on-surface-variant": "#444748",
        "surface-container-low": "#f6f3f2",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed": "#1c1b1b",
        "primary-container": "#212121",
        "primary": "#0a0a0a",
        "on-secondary-container": "#79422e",
        "on-tertiary-fixed": "#171e0d",
        "inverse-surface": "#313030",
        "on-primary-container": "#8a8888",
        "outline": "#747878",
        "tertiary-fixed-dim": "#c2caaf",
        "tertiary-fixed": "#dee6ca",
        "secondary": "#894f3b",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed": "#370e02",
        "surface-container-high": "#eae7e7",
        "tertiary-container": "#1c2312"
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px"
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        display: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"]
      },
    },
  },
  plugins: [],
}
